<?php 
/*
Plugin Name: Eventi
Plugin URI: https://losol.no/eventi
Description: Makes events a part of your site
Version: 0.1.1
Author: Ole Kristian Losvik
Author URI: https://losol.no
Text Domain: eventi
Generated By: http://ensuredomains.com
*/

// If this file is called directly, abort. //
if ( ! defined( 'WPINC' ) ) {die;} // end if
